version: '3'
services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: jenkins-nginx
    ports:
      - "20714:20714"
    volumes:
      - /usr/local/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/lcoal/nginx/conf/cert:/etc/nginx/cert
      - /usr/local/nginx/logs:/var/log/nginx
    networks:
      - jenkins-network
    restart: always
    command: [ "nginx", "-g", "daemon off;" ]
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-01
    user: root
    restart: always
    networks:
      - jenkins-network
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /opt/jenkins_home/:/var/jenkins_home

networks:
  jenkins-network:
    driver: bridge
